#' The package oneClass ...
#'
#' Write something ...
#' 
#' Write some more ...
#'
#' Short overview over the most important functions here ...
#' 
#' ...
#' 
#' @import caret
#' @importFrom dismo evaluate
#' @importFrom pROC roc
#' @docType package
#' @name oneClass
NULL