# ################################################################################
# #' @name print.holdOutPredictions
# #'
# #' @title Extract the held out predictions of a \code{\link{train}} or  \code{\link{oneClass}} object. .
# #'
# #' @description If both modParam, and modRow are \code{NULL} the held-out predictions of the 
# #' final model is returned.
# #'
# #' @param x a \code{holdOutPredictions} object.
# #' @return prints the \code{holdOutPredictions} object.
# #' @examples
# #' ### to do
# #' @export
# print.holdOutPredictions <- function (x, ...) {
#   browser()
#   ### ----------------------------------------------------------------------------
#   ### main fun
#   if (x$aggregate) {
#     cat(paste('Hold-out predictions generated by the', x$resampling$name, 'resampling approach.'))
#   } else {
#     cat(paste('Aggregated hold-out predictions generated by', x$resampling$name, 'resampling approach.'))
#   }
# }